### PR TITLE
first draft of B6's Page

### PR DESCRIPTION
**Pull request by leunami420**

### CODE REVIEW

**Comment by gefei** [comment]
Please have a look at your photos. Do you really need photos as large as 3400 x 2300 pixels?

**Comment by leunami420** [comment]
Oops sorry, I compressed the images, and will make sure to use a more reasonable Filesize for further images.

**Comment by gefei** [comment]
Please still make your photos smaller. There are still photos of more than 1400x1400 or even 2000x2000 pixels

**Comment by gefei** [comment]
Please make your photos still smaller. There are still photos of more than 1400x1400 or even 2000x2000 pixels

**Pull request closed without merging**
