### PR TITLE
Adjusted master project m1

### PR DESCRIPTION
**Pull request by shariebg**

### CODE REVIEW

**Comment by bkleinen** [comment]
Submodule showtime-theme-2021 updated from 827fa1 to 9b8c27 
This is a downgrade of the showtime-theme to 27.Jan....
please remove this from your branch.

**Review by bkleinen — CHANGES_REQUESTED** [review]
You downgrade the showtime to Jan 27th. please remove the change in 
 themes/showtime-theme-2021

**Comment by shariebg** [comment]
I used the following command to update theme submodule
`git submodule update`.
I'm sorry, but I'm not really sure how to remove this from our branch.

**Comment by shariebg** [comment]
Okay, I updated the showtime-theme to the lastest version

**Pull request merged**
